#!/bin/bash
#Kasutaja sisestab vanuse ja skript m22rab mis ikka ta kuulub"
if [ $# -ne 1 ]; then
	echo "K2ivita see skript koos vanusega. N2iteks $0 24"
else
vanus=$1
if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "Oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "Oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
	echo "Oled t2iskasvanu"
elif test $vanus -ge 63
then
	echo "Oled seenior"
else
	echo "Vigane sisend"
fi
fi
