#!/bin/bash

#Aja j2rgi tervitamine
echo -e "Sisesta aja v22rtus: \c"
read aeg
#kontrollime
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Tere hommikust!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere p2evast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere 6htust!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head 66d!"
else
	echo "Vigane sisend!"
fi
#Skripti l6pp
