#!/bin/bash
echo -n "Sisestasite suvaline taisarv: "
read arv
# arvutame jaak 2-ga jagamisel
jaak=$(( $arv % 2 ))
if [ $jaak -eq 0 ]
then
  echo "$arv on paaris"
else
  echo "$arv on paaritu"
fi
#tingimus kontoll on loppenud
