#!/bin/bash
#Kysin inimeste kogust
echo -n "Sisesta reisijate arv: "
read reisijad
#Kysin kohtade arvu bussis
echo -n "Sisesta kohtade arv bussis: "
read kohad
#Jagan  reisijate arvu bussis olevate kohtade arvuga
bussid=$(($reisijad / $kohad))
ylejaanud=$(($reisijad % $kohad))
if test $ylejaanud -gt 0
then
	bussid=$(($bussid + 1))
fi
#tulemuse v2ljastamine
echo "Kokku on vaja $bussid taisbussi"
#skripti l6pp

